/**
 * Shopee Listing 報告生成器
 * 將 ShopeeListing 轉換為可下載的 .txt 文本報告
 */

import type { ShopeeListing, DirectorOutput } from '../types/shopee';

// ============================================================================
// Full Shopee Listing Report
// ============================================================================

export function generateShopeeListingReport(
  listing: ShopeeListing,
  productName: string,
  directorOutput?: DirectorOutput | null,
): string {
  const lines: string[] = [
    '═══════════════════════════════════════════',
    '  蝦皮商品 Listing 完整報告',
    `  產品：${productName}`,
    `  生成時間：${new Date().toLocaleString('zh-TW')}`,
    '═══════════════════════════════════════════',
    '',
  ];

  // Visual strategy (if available)
  if (directorOutput) {
    lines.push('── 產品分析 ──');
    lines.push(`產品名稱：${directorOutput.productAnalysis.name}`);
    lines.push(`視覺描述：${directorOutput.productAnalysis.visualDescription}`);
    lines.push(`包裝顏色：${directorOutput.productAnalysis.packagingColors}`);
    lines.push(`偵測風格：${directorOutput.productAnalysis.detectedStyle}`);
    lines.push(`核心特色：${directorOutput.productAnalysis.keyFeaturesZh}`);
    lines.push('');
  }

  // SEO Titles
  lines.push('── SEO 標題 ──');
  for (const title of listing.seoTitles) {
    lines.push(`${title.seq}. ${title.title}`);
    lines.push(`   (${title.charCount} 字) 關鍵詞：${title.keywords}`);
    lines.push('');
  }

  // Product Description
  lines.push('── 產品描述 ──');
  lines.push(listing.productDescription);
  lines.push('');

  // SKU Bundles
  if (listing.skuBundles.length > 0) {
    lines.push('── SKU 組合建議 ──');
    for (const sku of listing.skuBundles) {
      lines.push(`${sku.emojiName} (${sku.sku})`);
      lines.push(`  內容：${sku.contents}`);
      lines.push(`  適合：${sku.targetBuyer}`);
      lines.push(`  建議：${sku.guidance}`);
      lines.push('');
    }
  }

  // Main Image Prompts
  lines.push('── 主圖 Prompt (6 張, 1024×1024) ──');
  for (const img of listing.mainImages) {
    lines.push(`${img.id} · ${img.title}`);
    lines.push(`  目的：${img.purpose}`);
    lines.push(`  Prompt：${img.promptText}`);
    lines.push('');
  }

  // Detail Image Prompts
  if (listing.detailImages.length > 0) {
    lines.push('── 詳情圖 Prompt (1024×1536) ──');
    for (const img of listing.detailImages) {
      lines.push(`${img.id} · ${img.title}`);
      lines.push(`  目的：${img.purpose}`);
      lines.push(`  Prompt：${img.promptText}`);
      lines.push('');
    }
  }

  // SKU Image Prompts
  if (listing.skuImages.length > 0) {
    lines.push('── SKU 圖 Prompt ──');
    for (const img of listing.skuImages) {
      lines.push(`${img.id} · ${img.title}`);
      lines.push(`  Prompt：${img.promptText}`);
      lines.push('');
    }
  }

  // Compliance Check
  lines.push('── 合規檢查 ──');
  if (listing.complianceCheck.length === 0) {
    lines.push('✓ 未檢測到禁用詞');
  } else {
    for (const item of listing.complianceCheck) {
      lines.push(`❌ ${item.originalWord} → ✅ ${item.replacement}`);
      lines.push(`   原因：${item.riskReason}`);
    }
  }
  lines.push('');

  lines.push('═══════════════════════════════════════════');
  lines.push('  Generated by AI-PM-Designer-Pro (Shopee Edition)');
  lines.push('═══════════════════════════════════════════');

  return lines.join('\n');
}

// ============================================================================
// Quick Text Export
// ============================================================================

export function generateListingTextSummary(listing: ShopeeListing, productName: string): string {
  const lines: string[] = [
    `=== ${productName} 蝦皮 Listing ===`,
    '',
    ...listing.seoTitles.map((t) => `${t.seq}. ${t.title}`),
    '',
    listing.productDescription,
  ];
  return lines.join('\n');
}
